# Generated by Django 2.2.1 on 2019-05-30 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20190527_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['rank', '-work_start'], 'verbose_name': 'עובד', 'verbose_name_plural': 'עובדים'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['initiator', 'name'], 'permissions': (('projects_profit', 'Projects profit'), ('project_list_pdf', 'Projects list PDF')), 'verbose_name': 'פרוייקט', 'verbose_name_plural': 'פרוייקטים'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'get_latest_by': 'date', 'ordering': ['date'], 'verbose_name': 'הרשמה'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'מע"מ'},
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=20, verbose_name='בנק'),
        ),
        migrations.AlterField(
            model_name='account',
            name='branch',
            field=models.CharField(max_length=20, verbose_name='סניף'),
        ),
        migrations.AlterField(
            model_name='account',
            name='branch_num',
            field=models.SmallIntegerField(verbose_name="מס' סניף"),
        ),
        migrations.AlterField(
            model_name='account',
            name='num',
            field=models.IntegerField(unique=True, verbose_name="מס' חשבון"),
        ),
        migrations.AlterField(
            model_name='account',
            name='payee',
            field=models.CharField(max_length=20, verbose_name='שם המוטב'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Employee', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Project', verbose_name='פרוייקט'),
        ),
        migrations.AlterField(
            model_name='activitybase',
            name='from_date',
            field=models.DateField(verbose_name='מתאריך'),
        ),
        migrations.AlterField(
            model_name='activitybase',
            name='new_meetings_from_phone_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' פגישות חדשות מתאום טלפוני"),
        ),
        migrations.AlterField(
            model_name='activitybase',
            name='office_meetings_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' פגישות במשרד"),
        ),
        migrations.AlterField(
            model_name='activitybase',
            name='recurring_meetings_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' פגישות חוזרות"),
        ),
        migrations.AlterField(
            model_name='activitybase',
            name='to_date',
            field=models.DateField(verbose_name='עד תאריך'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='amount',
            field=models.IntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='Management.EmployeeBase', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='שם הקובץ'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_private',
            field=models.BooleanField(blank=True, verbose_name='האם חסוי'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='sr_name',
            field=models.CharField(max_length=20, verbose_name='שם השולח/הנשלח'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='Management.Tag', verbose_name='תגיות נושא'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'נשלח'), (2, 'התקבל')], verbose_name='סוג מסמך'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user_added',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='משתמש'),
        ),
        migrations.AlterField(
            model_name='bdiscountsave',
            name='max_for_bonus',
            field=models.FloatField(blank=True, null=True, verbose_name="מקס' עבור בונוס"),
        ),
        migrations.AlterField(
            model_name='bdiscountsave',
            name='precentage_bonus',
            field=models.PositiveIntegerField(verbose_name='בונוס לאחוז'),
        ),
        migrations.AlterField(
            model_name='bdiscountsaveprecentage',
            name='max_for_bonus',
            field=models.FloatField(blank=True, null=True, verbose_name="מקס' עבור בונוס"),
        ),
        migrations.AlterField(
            model_name='bdiscountsaveprecentage',
            name='precentage_bonus',
            field=models.FloatField(verbose_name='בונוס לאחוז'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floors',
            field=models.PositiveSmallIntegerField(verbose_name="מס' קומות"),
        ),
        migrations.AlterField(
            model_name='building',
            name='house_count',
            field=models.PositiveSmallIntegerField(verbose_name='סה"כ מס\' יחידות'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='building',
            name='num',
            field=models.CharField(max_length=4, verbose_name="מס' בניין"),
        ),
        migrations.AlterField(
            model_name='building',
            name='pricelist',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='building', to='Management.Pricelist'),
        ),
        migrations.AlterField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='Management.Project', verbose_name='פרוייקט'),
        ),
        migrations.AlterField(
            model_name='building',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='building',
            name='stage',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='שלב'),
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.BuildingType', verbose_name='סוגי מבנים'),
        ),
        migrations.AlterField(
            model_name='camount',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='עמלה בשקלים'),
        ),
        migrations.AlterField(
            model_name='car',
            name='comprehensive_insurance_cost',
            field=models.IntegerField(verbose_name='עלות ביטוח מקיף'),
        ),
        migrations.AlterField(
            model_name='car',
            name='compulsory_insurance_cost',
            field=models.IntegerField(verbose_name='עלות ביטוח חובה'),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_expire_date',
            field=models.DateField(verbose_name='ת. תפוגת ביטוח'),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_man',
            field=models.CharField(max_length=20, verbose_name='סוכן ביטוח'),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_phone',
            field=models.CharField(max_length=10, verbose_name='טלפון ביטוח'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.IntegerField(unique=True, verbose_name="מס' רכב"),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(max_length=20, verbose_name='בעל רכב'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tow_company',
            field=models.CharField(max_length=20, verbose_name='חברת גרירה'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tow_phone',
            field=models.CharField(max_length=10, verbose_name='טלפון גרר'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='amount',
            field=models.IntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='division_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.DivisionType', verbose_name='חטיבה עסקית'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='expense_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.ExpenseType', verbose_name='סוג הוצאה'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='issue_date',
            field=models.DateField(verbose_name='ת. הוצאה'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='num',
            field=models.IntegerField(unique=True, verbose_name="מס' שיק"),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='pay_date',
            field=models.DateField(verbose_name='ת. תשלום'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='checkbase',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.CheckBaseType', verbose_name='חשבונית'),
        ),
        migrations.AlterField(
            model_name='checkbasetype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='citycallers',
            name='callers_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' מתקשרים"),
        ),
        migrations.AlterField(
            model_name='citycallers',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.City', verbose_name='עיר'),
        ),
        migrations.AlterField(
            model_name='clientstatustype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון סלולרי'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='חברה'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='פקס'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='דואר אלקטרוני'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='תפקיד'),
        ),
        migrations.AlterField(
            model_name='cprecentage',
            name='precentage',
            field=models.FloatField(verbose_name='עמלה באחוזים'),
        ),
        migrations.AlterField(
            model_name='cpriceamount',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='עמלה בשקלים'),
        ),
        migrations.AlterField(
            model_name='cpriceamount',
            name='price',
            field=models.PositiveIntegerField(verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='cvar',
            name='is_retro',
            field=models.BooleanField(verbose_name='רטרואקטיבי'),
        ),
        migrations.AlterField(
            model_name='cvarprecentage',
            name='is_retro',
            field=models.BooleanField(verbose_name='רטרואקטיבי'),
        ),
        migrations.AlterField(
            model_name='cvarprecentage',
            name='start_retro',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='רטרואקטיבי מדירה'),
        ),
        migrations.AlterField(
            model_name='cvarprecentagefixed',
            name='first_count',
            field=models.PositiveSmallIntegerField(verbose_name="מס' דירות ראשונות"),
        ),
        migrations.AlterField(
            model_name='cvarprecentagefixed',
            name='first_precentage',
            field=models.FloatField(verbose_name='עמלה באחוזים'),
        ),
        migrations.AlterField(
            model_name='cvarprecentagefixed',
            name='is_retro',
            field=models.BooleanField(verbose_name='רטרואקטיבי'),
        ),
        migrations.AlterField(
            model_name='cvarprecentagefixed',
            name='last_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="מס' דירות אחרונות"),
        ),
        migrations.AlterField(
            model_name='cvarprecentagefixed',
            name='last_precentage',
            field=models.FloatField(blank=True, null=True, verbose_name='עמלה באחוזים'),
        ),
        migrations.AlterField(
            model_name='cvarprecentagefixed',
            name='step',
            field=models.FloatField(verbose_name='מדרגה'),
        ),
        migrations.AlterField(
            model_name='czilber',
            name='b_discount',
            field=models.FloatField(verbose_name='בונוס חיסכון בהנחה'),
        ),
        migrations.AlterField(
            model_name='czilber',
            name='b_sale_rate',
            field=models.FloatField(verbose_name='בונוס קצב מכירות'),
        ),
        migrations.AlterField(
            model_name='czilber',
            name='b_sale_rate_max',
            field=models.FloatField(verbose_name='מקס עמלה'),
        ),
        migrations.AlterField(
            model_name='czilber',
            name='base',
            field=models.FloatField(verbose_name='עמלת בסיס'),
        ),
        migrations.AlterField(
            model_name='czilber',
            name='base_madad',
            field=models.FloatField(verbose_name='מדד בסיס'),
        ),
        migrations.AlterField(
            model_name='czilber',
            name='third_start',
            field=models.DateField(verbose_name='ת. תחילת שלישון'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='client_status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Management.ClientStatusType', verbose_name='סטטוס לקוח'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='commission',
            field=models.FloatField(blank=True, null=True, verbose_name='עמלה'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='commission_precentage',
            field=models.FloatField(blank=True, null=True, verbose_name='עמלה באחוזים'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='קומה'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rooms',
            field=models.FloatField(blank=True, null=True, verbose_name='חדרים'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='Management.Project', verbose_name='פרוייקט'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='sale_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="מס' מכירות"),
        ),
        migrations.AlterField(
            model_name='demand',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='demanddiff',
            name='amount',
            field=models.FloatField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='demanddiff',
            name='reason',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='סיבת הפרש'),
        ),
        migrations.AlterField(
            model_name='demanddiff',
            name='type',
            field=models.CharField(help_text='קבועה, משתנה, בונוס, קיזוז או לבחירתך', max_length=30, verbose_name='סוג הפרש'),
        ),
        migrations.AlterField(
            model_name='divisiontype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='main_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Management.Project', verbose_name='פרוייקט עיקרי'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, editable=False, related_name='employees', to='Management.Project', verbose_name='פרוייקטים'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.RankType', verbose_name='דרג'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='birth_date',
            field=models.DateField(verbose_name='תאריך לידה'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון סלולרי'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='child_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='מספר ילדים'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='family_state',
            field=models.PositiveIntegerField(choices=[(1, 'רווק'), (2, 'נשוי'), (3, 'גרוש'), (4, 'אלמן')], verbose_name='מצב משפחתי'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='home_phone',
            field=models.CharField(max_length=10, verbose_name='טלפון בבית'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='דואר אלקטרוני'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='mate_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון בן/בת זוג'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='pid',
            field=models.PositiveIntegerField(unique=True, verbose_name='ת.ז'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='תפקיד'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='work_end',
            field=models.DateField(blank=True, null=True, verbose_name='ת. סיום עבודה'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='work_fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='פקס באתר\\משרד'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='work_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון באתר\\משרד'),
        ),
        migrations.AlterField(
            model_name='employeebase',
            name='work_start',
            field=models.DateField(verbose_name='ת. תחילת עבודה'),
        ),
        migrations.AlterField(
            model_name='employeecheck',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='Management.EmployeeBase', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='employeecheck',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='employeecheck',
            name='purpose_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.PurposeType', verbose_name='מטרה'),
        ),
        migrations.AlterField(
            model_name='employeecheck',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='Management.Employee', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='base',
            field=models.FloatField(null=True, verbose_name='שכר בסיס'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='commissions',
            field=models.FloatField(editable=False, null=True, verbose_name='עמלות'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='deduction',
            field=models.FloatField(blank=True, null=True, verbose_name='קיזוז שכר'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='deduction_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='סיבת קיזוז'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], editable=False, verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='pdf_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות הדפסה'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='refund',
            field=models.FloatField(blank=True, null=True, verbose_name='החזר הוצאות'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='refund_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='סיבת ההחזר'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='safety_net',
            field=models.FloatField(blank=True, null=True, verbose_name='רשת בטחון'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='var_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='תוספת משתנה לעמלה'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='var_pay_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='סוג תוספת משתנה'),
        ),
        migrations.AlterField(
            model_name='employeesalarybase',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], editable=False, verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='hire_type',
            field=models.ForeignKey(help_text='לעצמאי יש להזין תנאי נכוי מס במקור', on_delete=django.db.models.deletion.PROTECT, to='Management.HireType', verbose_name='סוג העסקה'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='include_lawyer',
            field=models.BooleanField(blank=True, verbose_name='כולל ע"וד לעמלה'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='include_tax',
            field=models.BooleanField(blank=True, verbose_name='כולל מע"מ לעמלה'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='safety',
            field=models.PositiveIntegerField(verbose_name='רשת בטחון'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='salary_base',
            field=models.PositiveIntegerField(verbose_name='שכר בסיס'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='salary_net',
            field=models.NullBooleanField(choices=[(None, 'לא ידוע'), (False, 'ברוטו'), (True, 'נטו')], verbose_name='שכר נטו'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='tax_deduction_date',
            field=models.DateField(blank=True, null=True, verbose_name='ת. ניכוי'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='tax_deduction_source',
            field=models.NullBooleanField(choices=[(None, 'לא ידוע'), (False, 'פטור'), (True, 'יש')], verbose_name='נכוי מס במקור'),
        ),
        migrations.AlterField(
            model_name='employmentterms',
            name='tax_deduction_source_precentage',
            field=models.FloatField(blank=True, null=True, verbose_name='% נכוי מס במקור'),
        ),
        migrations.AlterField(
            model_name='epcommission',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך סיום'),
        ),
        migrations.AlterField(
            model_name='epcommission',
            name='max',
            field=models.FloatField(blank=True, null=True, verbose_name='מקס עמלה'),
        ),
        migrations.AlterField(
            model_name='epcommission',
            name='start_date',
            field=models.DateField(verbose_name='תאריך תחילה'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='משתתפים באירוע'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiator',
            field=models.CharField(max_length=50, verbose_name='יוזם האירוע'),
        ),
        migrations.AlterField(
            model_name='event',
            name='issues',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='נושאים לדיון'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='נושא האירוע'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='סיכום האירוע'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bruto_size',
            field=models.FloatField(blank=True, null=True, verbose_name='שטח ברוטו'),
        ),
        migrations.AlterField(
            model_name='house',
            name='building',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='Management.Building', verbose_name='בניין'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.PositiveSmallIntegerField(verbose_name='קומה'),
        ),
        migrations.AlterField(
            model_name='house',
            name='garden_size',
            field=models.FloatField(blank=True, null=True, verbose_name='גודל גינה/מרפסת'),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='האם נמכר?'),
        ),
        migrations.AlterField(
            model_name='house',
            name='load_precentage',
            field=models.FloatField(blank=True, null=True, verbose_name='אחוז העמסה'),
        ),
        migrations.AlterField(
            model_name='house',
            name='net_size',
            field=models.FloatField(verbose_name='שטח נטו'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num',
            field=models.CharField(max_length=5, verbose_name="מס' דירה"),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking_size',
            field=models.FloatField(blank=True, null=True, verbose_name='שטח חנייה'),
        ),
        migrations.AlterField(
            model_name='house',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.FloatField(verbose_name='חדרים'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.HouseType', verbose_name='סוג נכס'),
        ),
        migrations.AlterField(
            model_name='housetypebonus',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='housetypebonus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.HouseType', verbose_name='סוג דירה'),
        ),
        migrations.AlterField(
            model_name='houseversion',
            name='price',
            field=models.IntegerField(verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='houseversion',
            name='type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Management.PricelistType', verbose_name='סוג מחירון'),
        ),
        migrations.AlterField(
            model_name='income',
            name='client_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.ClientType', verbose_name='לקוח'),
        ),
        migrations.AlterField(
            model_name='income',
            name='division_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.DivisionType', verbose_name='חטיבה עסקית'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_producer_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.IncomeProducerType', verbose_name='מייצר הכנסה'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.IncomeType', verbose_name='סוג הכנסה'),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='income',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='incomeproducertype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='ת. חשבונית'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='num',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name="מס' חשבונית"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='invoiceoffset',
            name='amount',
            field=models.IntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='invoiceoffset',
            name='date',
            field=models.DateField(verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='invoiceoffset',
            name='reason',
            field=models.CharField(max_length=30, verbose_name='סיבה'),
        ),
        migrations.AlterField(
            model_name='invoiceoffset',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון סלולרי'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='דואר אלקטרוני'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='תפקיד'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=30, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(verbose_name='כתובת אינטרנט'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(help_text='התאריך המדויק של ההלוואה', null=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='Management.EmployeeBase', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='pay_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' תשלומים"),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='loanpay',
            name='amount',
            field=models.FloatField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='loanpay',
            name='deduct_from_salary',
            field=models.BooleanField(blank=True, choices=[(False, 'לא'), (True, 'כן')], help_text='האם יקוזז מהשכר של העובד', verbose_name='קזז מהשכר'),
        ),
        migrations.AlterField(
            model_name='loanpay',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_pays', to='Management.EmployeeBase', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='loanpay',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='loanpay',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='loanpay',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='madadbi',
            name='month',
            field=models.PositiveSmallIntegerField(verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='madadbi',
            name='publish_date',
            field=models.DateField(verbose_name='תאריך פרסום'),
        ),
        migrations.AlterField(
            model_name='madadbi',
            name='value',
            field=models.FloatField(verbose_name='ערך'),
        ),
        migrations.AlterField(
            model_name='madadbi',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='madadcp',
            name='month',
            field=models.PositiveSmallIntegerField(verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='madadcp',
            name='publish_date',
            field=models.DateField(verbose_name='תאריך פרסום'),
        ),
        migrations.AlterField(
            model_name='madadcp',
            name='value',
            field=models.FloatField(verbose_name='ערך'),
        ),
        migrations.AlterField(
            model_name='madadcp',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='mediareferrals',
            name='media',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Management.Media', verbose_name='מדיה'),
        ),
        migrations.AlterField(
            model_name='mediareferrals',
            name='referrals_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' פונים"),
        ),
        migrations.AlterField(
            model_name='nhactivity',
            name='nhbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHBranch', verbose_name='סניף'),
        ),
        migrations.AlterField(
            model_name='nhactivity',
            name='nhemployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHEmployee', verbose_name='עובד נייס האוס'),
        ),
        migrations.AlterField(
            model_name='nhbranch',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='nhbranch',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='פקס'),
        ),
        migrations.AlterField(
            model_name='nhbranch',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='דואר אלקטרוני'),
        ),
        migrations.AlterField(
            model_name='nhbranch',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='nhbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='nhbranch',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='כתובת אינטרנט'),
        ),
        migrations.AlterField(
            model_name='nhbranchemployee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך סיום'),
        ),
        migrations.AlterField(
            model_name='nhbranchemployee',
            name='is_manager',
            field=models.BooleanField(verbose_name='מנהל?'),
        ),
        migrations.AlterField(
            model_name='nhbranchemployee',
            name='nhbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHBranch', verbose_name='סניף'),
        ),
        migrations.AlterField(
            model_name='nhbranchemployee',
            name='nhemployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHEmployee', verbose_name='עובד נייס האוס'),
        ),
        migrations.AlterField(
            model_name='nhbranchemployee',
            name='start_date',
            field=models.DateField(verbose_name='תאריך תחילה'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='left_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='ערך'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='left_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='left_nhcommission_set', to='Management.NHSaleFilter', verbose_name='סינון'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='left_income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='left_nhcommission_set', to='Management.NHIncomeType', verbose_name='סוג הכנסה'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='name',
            field=models.CharField(max_length=30, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='nhbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHBranch', verbose_name='סניף'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='nhemployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHEmployee', verbose_name='עובד נייס האוס'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Management.Operator', verbose_name='אופרטור'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='right_amount',
            field=models.FloatField(verbose_name='ערך'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='right_amount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.AmountType', verbose_name='סוג ערך'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='right_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='right_nhcommission_set', to='Management.NHSaleFilter', verbose_name='סינון'),
        ),
        migrations.AlterField(
            model_name='nhcommission',
            name='right_income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='right_nhcommission_set', to='Management.NHIncomeType', verbose_name='סוג הכנסה'),
        ),
        migrations.AlterField(
            model_name='nhemployeesalary',
            name='nhbranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Management.NHBranch', verbose_name='סניף'),
        ),
        migrations.AlterField(
            model_name='nhemployeesalary',
            name='nhemployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='Management.NHEmployee', verbose_name='עובד נייס האוס'),
        ),
        migrations.AlterField(
            model_name='nhmonth',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='nhmonth',
            name='nhbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHBranch', verbose_name='סניף'),
        ),
        migrations.AlterField(
            model_name='nhmonth',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='nhpay',
            name='amount',
            field=models.FloatField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='address',
            field=models.CharField(max_length=50, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='floor',
            field=models.PositiveSmallIntegerField(verbose_name='קומה'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='hood',
            field=models.CharField(max_length=50, verbose_name='שכונה'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='num',
            field=models.IntegerField(unique=True, verbose_name="מס' עסקה"),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='price',
            field=models.FloatField(verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='rooms',
            field=models.FloatField(verbose_name='חדרים'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='sale_date',
            field=models.DateField(verbose_name='ת. מכירה'),
        ),
        migrations.AlterField(
            model_name='nhsale',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.HouseType', verbose_name='סוג דירה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='actual_commission',
            field=models.FloatField(verbose_name='% עמלה בפועל'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='address',
            field=models.CharField(max_length=40, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside_director', to='Management.EmployeeBase', verbose_name='גורם מפנה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='director_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='% עמלה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside1s', to='Management.NHEmployee', verbose_name='יועץ נדל"ן'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee1_commission',
            field=models.FloatField(verbose_name='% עמלה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside2s', to='Management.NHEmployee', verbose_name='יועץ נדל"ן'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee2_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='% עמלה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside3s', to='Management.NHEmployee', verbose_name='יועץ נדל"ן'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee3_commission',
            field=models.FloatField(blank=True, null=True, verbose_name='% עמלה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='employee_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות עובדים'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='income',
            field=models.IntegerField(blank=True, verbose_name='שווי תמורה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='lawyer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside1s', to='Management.Lawyer', verbose_name='עו"ד'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='lawyer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside2s', to='Management.Lawyer', verbose_name='עו"ד'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='name1',
            field=models.CharField(max_length=20, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='name2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='phone1',
            field=models.CharField(max_length=20, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='sale_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.SaleType', verbose_name='סוג פעולה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='signed_commission',
            field=models.FloatField(verbose_name='% עמלה חתום'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='signing_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nhsaleside_signer', to='Management.NHEmployee', verbose_name='יועץ מחתים'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='temp_receipt_num',
            field=models.IntegerField(verbose_name="מס' קבלה זמנית"),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='voucher_date',
            field=models.DateField(verbose_name='ת. הוצאת הזמנה'),
        ),
        migrations.AlterField(
            model_name='nhsaleside',
            name='voucher_num',
            field=models.IntegerField(verbose_name="מס' הזמנת שרותי תיווך"),
        ),
        migrations.AlterField(
            model_name='parking',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parkings', to='Management.Building', verbose_name='בניין'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parkings', to='Management.House', verbose_name='דירה'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' חנייה"),
        ),
        migrations.AlterField(
            model_name='parking',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.ParkingType', verbose_name='סוג חנייה'),
        ),
        migrations.AlterField(
            model_name='parkingcost',
            name='cost',
            field=models.FloatField(verbose_name='עלות'),
        ),
        migrations.AlterField(
            model_name='parkingcost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.ParkingType', verbose_name='סוג חנייה'),
        ),
        migrations.AlterField(
            model_name='parkingtype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='בנק'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='branch_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="מס' סניף"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name="מס' שיק"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='ת. תשלום'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.PaymentType', verbose_name='סוג תשלום'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='support_num',
            field=models.IntegerField(blank=True, null=True, verbose_name="מס' אסמכתא"),
        ),
        migrations.AlterField(
            model_name='paymentcheck',
            name='order_verifier',
            field=models.CharField(max_length=30, verbose_name='מאשר ההזמנה'),
        ),
        migrations.AlterField(
            model_name='paymentcheck',
            name='payment_verifier',
            field=models.CharField(max_length=30, verbose_name='מאשר התשלום'),
        ),
        migrations.AlterField(
            model_name='paymentcheck',
            name='supplier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.SupplierType', verbose_name='ספק'),
        ),
        migrations.AlterField(
            model_name='paymentcheck',
            name='tax_deduction_source',
            field=models.IntegerField(blank=True, null=True, verbose_name='נכוי מס במקור'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='allowed_discount',
            field=models.FloatField(default=0, verbose_name='% הנחת מו"מ מאושר'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='guarantee_amount',
            field=models.FloatField(default=0, verbose_name='סכות ערבות'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='include_guarantee',
            field=models.NullBooleanField(verbose_name='כולל ערבות'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='include_lawyer',
            field=models.NullBooleanField(verbose_name='כולל ע"וד'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='include_parking',
            field=models.NullBooleanField(verbose_name='כולל חנייה'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='include_registration',
            field=models.NullBooleanField(verbose_name='כולל הוצאות רישום'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='include_storage',
            field=models.NullBooleanField(verbose_name='כולל מחסן'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='include_tax',
            field=models.NullBooleanField(verbose_name='כולל מעמ'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_permit',
            field=models.NullBooleanField(verbose_name='יש היתר'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='lawyer_fee',
            field=models.FloatField(default=0, verbose_name='שכר טרחת עו"ד'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='permit_date',
            field=models.DateField(blank=True, null=True, verbose_name='ת. קבלת היתר'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='register_amount',
            field=models.FloatField(default=0, verbose_name='הוצאות רישום'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='settle_date',
            field=models.DateField(blank=True, null=True, verbose_name='מועד אכלוס'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='storage_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='עלות מחסן'),
        ),
        migrations.AlterField(
            model_name='pricelisttype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='address',
            field=models.CharField(max_length=50, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='clients',
            field=models.CharField(max_length=50, verbose_name='שמות הרוכשים'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='commission_buyer',
            field=models.FloatField(verbose_name='עמלת קונה'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='commission_seller',
            field=models.FloatField(verbose_name='עמלת מוכר'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='nhemployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHEmployee', verbose_name='עובד נייס האוס'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='price_offered',
            field=models.IntegerField(verbose_name='מחיר שהוצע'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='price_wanted',
            field=models.IntegerField(verbose_name='מחיר רצוי'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='priceoffer',
            name='rooms',
            field=models.FloatField(verbose_name='חדרים'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cell_phone',
            field=models.CharField(max_length=15, verbose_name='טלפון סלולרי בפרוייקט'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=30, verbose_name='עיר'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך סיום'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fax',
            field=models.CharField(max_length=15, verbose_name='פקס בפרוייקט'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hood',
            field=models.CharField(max_length=30, verbose_name='שכונה'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initiator',
            field=models.CharField(max_length=30, verbose_name='יזם'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_marketing',
            field=models.BooleanField(choices=[(False, 'לא'), (True, 'כן')], verbose_name='בשיווק?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='דואר אלקטרוני'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, verbose_name='שם הפרוייקט'),
        ),
        migrations.AlterField(
            model_name='project',
            name='office_address',
            field=models.CharField(max_length=30, verbose_name='כתובת המשרד'),
        ),
        migrations.AlterField(
            model_name='project',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='טלפון בפרוייקט'),
        ),
        migrations.AlterField(
            model_name='project',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות מיוחדות'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='תאריך תחילה'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='add_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='סכום תוספת'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='add_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='סוג תוספת'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='קובץ ההסכם'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='commission_by_signups',
            field=models.BooleanField(blank=True, verbose_name='עמלה לפי הרשמות?'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='deduct_registration',
            field=models.NullBooleanField(choices=[(None, 'לא משנה'), (False, 'לא'), (True, 'כן')], verbose_name='קזז הוצאות רישום לאחר משפטיות'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='include_lawyer',
            field=models.NullBooleanField(choices=[(None, 'לא משנה'), (False, 'לא'), (True, 'כן')], verbose_name='כולל ע"וד לעמלה'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='include_tax',
            field=models.NullBooleanField(default=True, verbose_name='כולל מע"מ לעמלה'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='max',
            field=models.FloatField(blank=True, null=True, verbose_name='מקס עמלה'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='registration_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='הוצאות רישום'),
        ),
        migrations.AlterField(
            model_name='projectcommission',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='נקודות חשובות להסכם'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='architect',
            field=models.CharField(max_length=30, verbose_name='שם האדריכל'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='bank',
            field=models.CharField(max_length=20, verbose_name='בנק מלווה'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='building_types',
            field=models.ManyToManyField(to='Management.BuildingType', verbose_name='סוגי מבנים'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='buildings_num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' מבנים"),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='houses_num',
            field=models.PositiveSmallIntegerField(verbose_name='סה"כ מס\' יחידות'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='כתובת אינטרנט'),
        ),
        migrations.AlterField(
            model_name='purposetype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='ranktype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='דרג'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='content',
            field=models.TextField(verbose_name='תוכן'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='compensation_allocation',
            field=models.FloatField(verbose_name='הפרשות לפיצויים'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='convalescence_pay',
            field=models.FloatField(verbose_name='דמי הבראה'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.EmployeeBase', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='employer_benefit',
            field=models.FloatField(verbose_name='גמול מעביד'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='employer_national_insurance',
            field=models.FloatField(verbose_name='ביטוח לאומי מעביד'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='health',
            field=models.FloatField(verbose_name='בריאות'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='income_tax',
            field=models.FloatField(verbose_name='מס הכנסה'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='national_insurance',
            field=models.FloatField(verbose_name='ביטוח לאומי'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='pension_insurance',
            field=models.FloatField(verbose_name='ביטוח פנסיה'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='vacation',
            field=models.FloatField(verbose_name='חופשה'),
        ),
        migrations.AlterField(
            model_name='salaryexpenses',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='allowed_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='% הנחת מו"מ מאושר'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='clients',
            field=models.TextField(verbose_name='שמות הרוכשים'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='clients_phone',
            field=models.CharField(max_length=10, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission_include',
            field=models.BooleanField(blank=True, default=True, verbose_name='לחישוב עמלה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission_madad_bi',
            field=models.FloatField(blank=True, null=True, verbose_name='מדד לחישוב עמלה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='מחיר מחירון חברה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='contract_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='מס\' חוזה ש"ע'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='contractor_pay_month',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='חודש תשלום לקבלן'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='contractor_pay_year',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='שנת תשלום לקבלן'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='% הנחה בלוח תשלומים'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Management.Employee', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee_pay_month',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='חודש תשלום לעובד'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee_pay_year',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='שנת תשלום לעובד'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='Management.House', verbose_name='דירה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='include_registration',
            field=models.NullBooleanField(choices=[(None, 'לא משנה'), (False, 'לא'), (True, 'כן')], default=None, verbose_name='כולל הוצאות רישום'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='include_tax',
            field=models.BooleanField(choices=[(False, 'לא'), (True, 'כן')], default=True, verbose_name='כולל מעמ'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='other_expense',
            field=models.PositiveIntegerField(default=0, verbose_name='הוצאות אחרות'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.IntegerField(verbose_name='מחיר חוזה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_include_lawyer',
            field=models.BooleanField(choices=[(False, 'לא'), (True, 'כן')], verbose_name='מחיר כולל ע"וד'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_no_lawyer',
            field=models.IntegerField(verbose_name='מחיר חוזה ללא ע"וד'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='ת. מכירה'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='specification_expense',
            field=models.PositiveIntegerField(default=0, verbose_name='הוצאות מפרט'),
        ),
        migrations.AlterField(
            model_name='salecancel',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='salecancel',
            name='deduct_from_demand',
            field=models.BooleanField(blank=True, verbose_name='קזז מהדרישה'),
        ),
        migrations.AlterField(
            model_name='salecancel',
            name='remarks',
            field=models.TextField(null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='salehousemod',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='salehousemod',
            name='remarks',
            field=models.TextField(null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='salepre',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='salepre',
            name='employee_pay_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש תשלום לעובד'),
        ),
        migrations.AlterField(
            model_name='salepre',
            name='employee_pay_year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנת תשלום לעובד'),
        ),
        migrations.AlterField(
            model_name='salepre',
            name='remarks',
            field=models.TextField(null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='salepre',
            name='to_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש דחייה'),
        ),
        migrations.AlterField(
            model_name='salepre',
            name='to_year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנת דחייה'),
        ),
        migrations.AlterField(
            model_name='salepricemod',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='salepricemod',
            name='remarks',
            field=models.TextField(null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Building', verbose_name='בניין'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.House', verbose_name='דירה'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='objection',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='התנגדויות'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='price',
            field=models.IntegerField(verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Project', verbose_name='פרוייקט'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='saleratebonus',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='עמלה בשקלים'),
        ),
        migrations.AlterField(
            model_name='saleratebonus',
            name='house_count',
            field=models.PositiveSmallIntegerField(verbose_name="מס' דירות"),
        ),
        migrations.AlterField(
            model_name='salereject',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='salereject',
            name='employee_pay_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש תשלום לעובד'),
        ),
        migrations.AlterField(
            model_name='salereject',
            name='employee_pay_year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנת תשלום לעובד'),
        ),
        migrations.AlterField(
            model_name='salereject',
            name='remarks',
            field=models.TextField(null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='salereject',
            name='to_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='חודש דחייה'),
        ),
        migrations.AlterField(
            model_name='salereject',
            name='to_year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], verbose_name='שנת דחייה'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='clients',
            field=models.TextField(verbose_name='שמות הרוכשים'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='clients_address',
            field=models.TextField(null=True, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='clients_phone',
            field=models.TextField(verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateField(verbose_name='ת. הרשמה'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signups', to='Management.Employee', verbose_name='עובד'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signups', to='Management.House', verbose_name='דירה'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='price',
            field=models.IntegerField(verbose_name='ת. הרשמה'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='price_include_lawyer',
            field=models.BooleanField(choices=[(False, 'לא'), (True, 'כן')], verbose_name='כולל ע"וד'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='sale_date',
            field=models.DateField(verbose_name='ת. מכירה'),
        ),
        migrations.AlterField(
            model_name='signupcancel',
            name='date',
            field=models.DateField(verbose_name='ת. ביטול'),
        ),
        migrations.AlterField(
            model_name='signupcancel',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='סיבת הביטול'),
        ),
        migrations.AlterField(
            model_name='signupcancel',
            name='was_fee',
            field=models.BooleanField(choices=[(False, 'לא'), (True, 'כן')], verbose_name='האם היה קנס'),
        ),
        migrations.AlterField(
            model_name='signupcancel',
            name='was_signed',
            field=models.BooleanField(choices=[(False, 'לא'), (True, 'כן')], verbose_name='האם הוחתם על טופס ביטול'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storages', to='Management.Building', verbose_name='בניין'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storages', to='Management.House', verbose_name='דירה'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='num',
            field=models.PositiveSmallIntegerField(verbose_name="מס' מחסן"),
        ),
        migrations.AlterField(
            model_name='storage',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='suppliertype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(verbose_name='תוכן'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='משתמש'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='date',
            field=models.DateField(verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='value',
            field=models.FloatField(verbose_name='ערך'),
        ),
    ]
