# Generated by Django 2.2.1 on 2019-07-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20190530_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecancel',
            name='deduct_from_demand',
            field=models.BooleanField(blank=True, null=True, verbose_name='קזז מהדרישה'),
        ),
    ]
