# Generated by Django 2.2.1 on 2019-07-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20190701_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
