# Generated by Django 2.2.3 on 2019-07-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20190720_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='client_status_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='income',
            name='division_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_producer_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_type',
        ),
        migrations.RemoveField(
            model_name='income',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment',
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
        migrations.DeleteModel(
            name='ClientStatusType',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeProducerType',
        ),
        migrations.DeleteModel(
            name='IncomeType',
        ),
    ]
