# Generated by Django 2.2.3 on 2019-07-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20190722_0819'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='MadadBI',
                ),
                migrations.DeleteModel(
                    name='MadadCP',
                ),
                migrations.DeleteModel(
                    name='Tax',
                ),
            ],
        ),
    ]