# Generated by Django 2.2.3 on 2019-07-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20190723_1114'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='citycallers',
                    name='activity_base',
                ),
                migrations.RemoveField(
                    model_name='citycallers',
                    name='city',
                ),
                migrations.RemoveField(
                    model_name='event',
                    name='activity_base',
                ),
                migrations.RemoveField(
                    model_name='mediareferrals',
                    name='activity_base',
                ),
                migrations.RemoveField(
                    model_name='mediareferrals',
                    name='media',
                ),
                migrations.RemoveField(
                    model_name='nhactivity',
                    name='activitybase_ptr',
                ),
                migrations.RemoveField(
                    model_name='nhactivity',
                    name='nhbranch',
                ),
                migrations.RemoveField(
                    model_name='nhactivity',
                    name='nhemployee',
                ),
                migrations.RemoveField(
                    model_name='priceoffer',
                    name='nhactivity',
                ),
                migrations.RemoveField(
                    model_name='priceoffer',
                    name='nhemployee',
                ),
                migrations.RemoveField(
                    model_name='saleprocess',
                    name='activity_base',
                ),
                migrations.RemoveField(
                    model_name='saleprocess',
                    name='building',
                ),
                migrations.RemoveField(
                    model_name='saleprocess',
                    name='house',
                ),
                migrations.RemoveField(
                    model_name='saleprocess',
                    name='project',
                ),
                migrations.DeleteModel(
                    name='Activity',
                ),
                migrations.DeleteModel(
                    name='ActivityBase',
                ),
                migrations.DeleteModel(
                    name='City',
                ),
                migrations.DeleteModel(
                    name='CityCallers',
                ),
                migrations.DeleteModel(
                    name='Event',
                ),
                migrations.DeleteModel(
                    name='Media',
                ),
                migrations.DeleteModel(
                    name='MediaReferrals',
                ),
                migrations.DeleteModel(
                    name='NHActivity',
                ),
                migrations.DeleteModel(
                    name='PriceOffer',
                ),
                migrations.DeleteModel(
                    name='SaleProcess',
                ),
            ],
        ),
    ]