# Generated by Django 2.2.3 on 2019-07-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkbase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='checkbasetype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employeecheck',
            table=None,
        ),
        migrations.AlterModelTable(
            name='expensetype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentcheck',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purposetype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='suppliertype',
            table=None,
        ),
    ]
