# Generated by Django 2.2.3 on 2019-07-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0008_auto_20190724_0842'),
    ]

    operations=[
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ActivityBase',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('from_date', models.DateField(verbose_name='מתאריך')),
                        ('to_date', models.DateField(verbose_name='עד תאריך')),
                        ('office_meetings_num', models.PositiveSmallIntegerField(verbose_name="מס' פגישות במשרד")),
                        ('recurring_meetings_num', models.PositiveSmallIntegerField(verbose_name="מס' פגישות חוזרות")),
                        ('new_meetings_from_phone_num', models.PositiveSmallIntegerField(verbose_name="מס' פגישות חדשות מתאום טלפוני")),
                    ],
                    options={
                        'db_table': 'ActivityBase',
                    },
                ),
                migrations.CreateModel(
                    name='City',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=20, unique=True, verbose_name='שם')),
                    ],
                    options={
                        'db_table': 'City',
                    },
                ),
                migrations.CreateModel(
                    name='Media',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=20, unique=True, verbose_name='שם')),
                    ],
                    options={
                        'db_table': 'Media',
                    },
                ),
                migrations.CreateModel(
                    name='NHActivity',
                    fields=[
                        ('activitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Activity.ActivityBase')),
                        ('nhbranch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHBranch', verbose_name='סניף')),
                        ('nhemployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHEmployee', verbose_name='עובד נייס האוס')),
                    ],
                    options={
                        'db_table': 'NHActivity',
                    },
                    bases=('Activity.activitybase',),
                ),
                migrations.CreateModel(
                    name='SaleProcess',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('price', models.IntegerField(verbose_name='מחיר')),
                        ('objection', models.TextField(blank=True, max_length=200, null=True, verbose_name='התנגדויות')),
                        ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות')),
                        ('activity_base', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Activity.ActivityBase')),
                        ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Building', verbose_name='בניין')),
                        ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.House', verbose_name='דירה')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Project', verbose_name='פרוייקט')),
                    ],
                    options={
                        'db_table': 'SaleProcess',
                    },
                ),
                migrations.CreateModel(
                    name='MediaReferrals',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('referrals_num', models.PositiveSmallIntegerField(verbose_name="מס' פונים")),
                        ('activity_base', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Activity.ActivityBase')),
                        ('media', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Activity.Media', verbose_name='מדיה')),
                    ],
                    options={
                        'db_table': 'MediaReferrals',
                    },
                ),
                migrations.CreateModel(
                    name='Event',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateTimeField(verbose_name='תאריך')),
                        ('initiator', models.CharField(max_length=50, verbose_name='יוזם האירוע')),
                        ('subject', models.CharField(max_length=50, verbose_name='נושא האירוע')),
                        ('attendees', models.TextField(blank=True, max_length=200, null=True, verbose_name='משתתפים באירוע')),
                        ('summary', models.TextField(blank=True, max_length=200, null=True, verbose_name='סיכום האירוע')),
                        ('issues', models.TextField(blank=True, max_length=200, null=True, verbose_name='נושאים לדיון')),
                        ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות')),
                        ('activity_base', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Activity.ActivityBase')),
                    ],
                    options={
                        'db_table': 'Event',
                        'ordering': ['date'],
                    },
                ),
                migrations.CreateModel(
                    name='CityCallers',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('callers_num', models.PositiveSmallIntegerField(verbose_name="מס' מתקשרים")),
                        ('activity_base', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Activity.ActivityBase')),
                        ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Activity.City', verbose_name='עיר')),
                    ],
                    options={
                        'db_table': 'CityCallers',
                    },
                ),
                migrations.CreateModel(
                    name='PriceOffer',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('address', models.CharField(max_length=50, verbose_name='כתובת')),
                        ('rooms', models.FloatField(verbose_name='חדרים')),
                        ('clients', models.CharField(max_length=50, verbose_name='שמות הרוכשים')),
                        ('price_wanted', models.IntegerField(verbose_name='מחיר רצוי')),
                        ('price_offered', models.IntegerField(verbose_name='מחיר שהוצע')),
                        ('commission_seller', models.FloatField(verbose_name='עמלת מוכר')),
                        ('commission_buyer', models.FloatField(verbose_name='עמלת קונה')),
                        ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='הערות')),
                        ('nhemployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.NHEmployee', verbose_name='עובד נייס האוס')),
                        ('nhactivity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Activity.NHActivity')),
                    ],
                    options={
                        'db_table': 'PriceOffer',
                    },
                ),
                migrations.CreateModel(
                    name='Activity',
                    fields=[
                        ('activitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Activity.ActivityBase')),
                        ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Employee', verbose_name='עובד')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.Project', verbose_name='פרוייקט')),
                    ],
                    options={
                        'db_table': 'Activity',
                    },
                    bases=('Activity.activitybase',),
                ),
            ],
        ),
    ]