# Generated by Django 2.2.3 on 2019-07-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitybase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='citycallers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='media',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mediareferrals',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nhactivity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='priceoffer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='saleprocess',
            table=None,
        ),
    ]
