# Generated by Django 2.2.3 on 2019-07-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='madadbi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='madadcp',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tax',
            table=None,
        ),
    ]
